export class PathConstants {
    public static readonly librarienregister_Post='librarienregister/Post';
    public static readonly categorymaster_Get='BookCategoryMaster';
    public static readonly book_Post='Book/Post';
    public static readonly book_Get='Book';
    public static readonly update_Post='updatebookmaster/Post';
    public static readonly studentreg_Post='Studentreg/Post';
    public static readonly studentreg_Get='Studentreg';
    public static readonly gendermaster_Get='GenderMaster';
    public static readonly collegemaster_Get='CollegeMaster';
    public static readonly coursemaster_Post='CourseMaster/Post';
    public static readonly coursemaster_Get='CourseMaster';
    public static readonly updatecourse_Post='updatecoursemaster/Post';
    public static readonly department_Get='DepartmentMaster';
    public static readonly getlibrarienregister_Get ='librarienregisterget/GetLibrarienRegister';
    public static readonly languagemaster_Post ='LanguageMaster/Post'
    public static readonly Entity_Post ='BookCategoryMaster/Post'
    //public static readonly GetBookCategoryMaster_Get='BookCategoryMaster';
    public static readonly CollegeMasterEntity_Post='CollegeMaster/Post';
    public static readonly updatecollegemaster_Post='UpdateCollegeMaster/Post';
    public static readonly DepartmentMasterEntity_Post='DepartmentMaster/Post';
    public static readonly languagemaster_Get='LanguageMaster';
    public static readonly updatelanguage_Post='updatelanguagemaster/Post';
    public static readonly editionmaster_Post='BookEdition/Post';
    public static readonly editionmaster_Get='BookEdition';
    public static readonly updateedition_Post='updateeditionmaster/Post';
    public static readonly StudentreqEntity_Post='studentRequest/Post';
    public static readonly Getstudentreq='studentRequest';
}